# Generated by Django 3.1.7 on 2021-04-29 11:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='images',
            field=models.ImageField(default=datetime.datetime(2021, 4, 29, 11, 34, 32, 589820, tzinfo=utc), upload_to='media/'),
        ),
    ]
