# Generated by Django 3.1.7 on 2021-05-03 13:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_auto_20210503_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='recipes',
            name='images',
            field=models.ImageField(default=datetime.datetime(2021, 5, 3, 13, 7, 36, 452676, tzinfo=utc), upload_to='media/'),
        ),
    ]
